### ISSUE TITLE
Suggestion for usage of '_tmp' dir.

### ISSUE THREAD

**Issue by OkuyanBoga** [deepppl/stan-num-pyro#1]
Hello,
I think it is not a good idea forcing users to create and use the '_tmp' folder because some users might want to use a custom directory.
It would be better if users can provide the build_dir during init.

https://github.com/deepppl/stan-num-pyro/blob/d7735c013d88eedff6af02ac0d6f635cb83fc7cd/stan-numpyro/stannumpyro/dppl.py#L43-L54

Suggestion:
```python
 class NumPyroModel: 
     def __init__( 
         self, stanfile, recompile=True, mode="comprehensive", compiler=["stanc"],build_dir="_tmp"
     ): 
         if build_dir == "_tmp":
             if not os.path.exists("_tmp"): 
                 os.makedirs("_tmp") 
                 pathlib.Path("_tmp/__init__.py").touch() 
  
         modname = compile(mode, stanfile, compiler, recompile, build_dir) 
  
         self.module = importlib.import_module(modname) 
```

**Comment by gbdrt** [comment]
Thanks for the suggestion!
This should now be possible: see b33d3683
